#!/bin/sh

export VERBOSE=1

_v() {
    [ -n "$VERBOSE" ] && [ "$VERBOSE" -ge 1 ] && echo "$*" >&2
}

v() {
    _v "$(date) upgrade: $@"
}


. /lib/upgrade/platform.sh
echo "$(date) Performing firmware upgrade"

v "Performing system upgrade..."
if type 'platform_do_upgrade' >/dev/null 2>/dev/null; then
	platform_do_upgrade "$IMAGE"
else
	default_do_upgrade "$IMAGE"
fi

if [ -n "$UPGRADE_BACKUP" ] && type 'platform_copy_config' >/dev/null 2>/dev/null; then
	platform_copy_config
fi

v "Upgrade completed"
#sleep 1
dual_boot=$(cat /sys/module/boot_param/parameters/dual_boot 2>/dev/null)

if [ x"${dual_boot}" != xY ]; then
v "Rebooting system..."
umount -a
reboot -f
sleep 5
echo b 2>/dev/null >/proc/sysrq-trigger
fi